export const actionTypes = {
  CREATE_COURSE: 'CREATE_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  LOAD_COURSES: 'LOAD_COURSES',

  CREATE_AUTHOR: 'CREATE_AUTHOR',
  DELETE_AUTHOR: 'DELETE_AUTHOR',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
  LOAD_AUTHORS: 'LOAD_AUTHORS',
};
